server:
  port: 8080

spring:
  application:
    name: pdelivery
  datasource:
    username:
    password:
    url:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

app:
  jwt:
    secret: "passion-delivery-jwt-secret-key-must-be-at-least-32-characters"
    expiration-ms: 3600000
  master:
    username: master
    password: Master1234!
    nickname: 마스터
    email: master@pdelivery.com
